CREATE TABLE IF NOT EXISTS `comfyUsageLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userEmail` varchar(320),
	`userName` varchar(255),
	`ip` varchar(64) NOT NULL,
	`action` varchar(64) NOT NULL,
	`baseUrl` varchar(512) NOT NULL,
	`host` varchar(255),
	`model` varchar(255),
	`projectId` int,
	`nodeId` varchar(255),
	`status` varchar(16) NOT NULL,
	`durationMs` int,
	`resultUrl` varchar(2048),
	`resultCount` int,
	`errorMessage` varchar(1024),
	`detail` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `comfyUsageLogs_id` PRIMARY KEY(`id`),
	INDEX `comfyUsageLogs_userId_idx` (`userId`),
	INDEX `comfyUsageLogs_host_idx` (`host`),
	INDEX `comfyUsageLogs_status_idx` (`status`),
	INDEX `comfyUsageLogs_createdAt_idx` (`createdAt`)
);
