CREATE TABLE IF NOT EXISTS `llmUsageLogs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `userId` int,
  `userName` varchar(255),
  `scene` varchar(128) NOT NULL DEFAULT 'unknown',
  `model` varchar(128),
  `route` varchar(24) NOT NULL DEFAULT 'platform',
  `status` varchar(16) NOT NULL,
  `errorMessage` varchar(1024),
  `durationMs` int,
  `promptChars` int,
  `replyChars` int,
  `promptText` text,
  `replyText` text,
  `projectId` int,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `llmUsageLogs_id` PRIMARY KEY(`id`),
  INDEX `llmUsageLogs_userId_idx` (`userId`),
  INDEX `llmUsageLogs_scene_idx` (`scene`),
  INDEX `llmUsageLogs_model_idx` (`model`),
  INDEX `llmUsageLogs_status_idx` (`status`),
  INDEX `llmUsageLogs_createdAt_idx` (`createdAt`)
);
